spring.application.name=Day70_springboot

server.port=8090
# 스프링부트의 설정 파일
# 서버 동작 방식을 정하는 파일!
# 스프링 부트가 시작될때 제일 먼저 읽는 파일이다!

spring.datasource.url=jdbc:mysql://mysql:3306/testdb?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA 설정 
# JPA가 테이블을 어떻게 관리할 지 정하는 설정이다!
# 테이블이 없으면 - 생성 
# 컬럼명 바뀌면 - 자동으로 반영
# 데이터도 유지한다.
spring.jpa.hibernate.ddl-auto=update

#JPA가 자동으로 SQL언어를 작성해준다. 콘솔에 출력해주는 설정
# sql언어 한줄로 나오는 단점!
spring.jpa.show-sql=true

# SQL 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true

# 실행된 sql 을 아주 자세히 출력 
logging.level.org.hibernate.SQL=trace
logging.level.org.hibernate.type.descriptor.sql=trace

# ? 에 값이 안보일 수도 있다! 버전 차이를 의심해야된다!
logging.level.org.hibernate.orm.jdbc.bind=trace
